### ISSUE TITLE
Bug: API query fails when the supportPhoneNumber attribute is not returned

### ISSUE THREAD

**Issue by bushvin** [cyberjunky/python-shellrecharge#2]
When querying an EV charger, your code fails because `supportPhoneNumber` is a mandatory attribute for the `Location` class.

IMO it should not be mandatory, and I have created a [PR](https://github.com/cyberjunky/python-shellrecharge/pull/1) to fix that.

**Comment by cyberjunky** [comment]
@bushvin should be fixed now in latest version

**Comment by cyberjunky** [comment]
Issue closed, stale.
