### ISSUE TITLE
Feature: charge-point interaction

### ISSUE THREAD

**Issue by Crazy-Duck** [cyberjunky/python-shellrecharge#3]
I've got working python code that allows interaction with private charge points. I've got a function that, provided an email and password, generates an api key which then can be used to fetch cards, private charge points and start/stop sessions on the charge point. I'd like to integrate the code in this repo as a first step to offering corresponding sensors and services in home assistant. Which way would you like me to go about this? Do I create a separate class for the authenticated functions? Do I integrate it in the existing class?

**Comment by cyberjunky** [comment]
Added to version 0.1.18, thanks!
